services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
    #ports:
      #- "5000:5000" # Uncomment to expose the application on your host
    volumes:
      - ../files/logvolume:/app/logs
    command: >
      sh -c "flask init-db &&
             flask run --host=0.0.0.0"