version: '3.8'

services:
  web:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    #ports:
      #- "5000:5000" # Uncomment to expose the application on your host
    volumes:
      - ../files/logvolume:/app/logs
    command: >
      sh -c "flask init-db &&
             flask run --host=0.0.0.0"